name: Linter Runner

# Run on push and pull request
on: 
  - push
  - pull_request

jobs:
  eslint:
    name: Linter Runner
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Run Linter
      - name: Install dependencies
        run: 
            npm install eslint
            npm install eslint-config-airbnb-base
            npm install eslint-plugin-import 
            npm install eslint-plugin-jest
      - name: Run tests
        run: 
            make test
      - name: Run linter
        run: make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
